### ISSUE TITLE
Target casbin to wasm

### ISSUE THREAD

**Issue by xcaptain** [casbin/casbin-rs#101]
We usually use casbin-rs in a web server, that is when a request comes in, a middleware or controller asks casbin whether it's authenticated. A common situation is that we also have a frontend ui that needs to do permission control. If we can compile casbin to wasm file, then we can do enforce at browser, no need to ask for the server all the time.

Rust has very good wasm support, I think this idea can be implemented. After that we need to consider how to sync user's policy from server, maybe we need to add a `get_all_policies_for_user` in `internal_api.rs`

**Comment by xcaptain** [comment]
First trial failed, because casbin depends on tokio depends on mio depends on net2, and net2 doesn't compile on wasm32-unknown-unknown. To achieve this we may need to have a very simple core and build other depencies on top of this core.

**Comment by PsiACE** [comment]
I like option 1, more lightweight, better structure.

**Comment by GopherJ** [comment]
I would say we can have a `synchronous` feature or `wasm` feature, All the adapters can also implement this feature.

If someone is interested in this please comment below.

**Comment by parqbanq** [comment]
Currently using [CASL](https://github.com/stalniy/casl)  in js, which is 'isomorphic'. Looking for something similar in rust, so yes, interested.

**Comment by hsluoyz** [comment]
We had a plan for developing casbin.js, which is based on Node-casbin because of the JS language: https://github.com/casbin/casbin.js/issues/2 . We may even have a GSoC student to work on it this year: https://github.com/casbin/SummerOfCode2020#casbinjs

Of course it's also welcome if Casbin-RS can achieves front-end authorization too via WASM!

**Comment by parqbanq** [comment]
@hsluoyz That's even better I suppose as at this stage many solutions will have rust for backend and js in the client.

**Comment by GopherJ** [comment]
async-std = "1.6.0-beta.1"     # Async version of the Rust standard library

has been published with `smol` as runtime, so we can retry to add `wasm` support. @xcaptain

**Comment by GopherJ** [comment]
I'll try to upgrade `async-std` to `1.6.0-beta.1`

**Comment by GopherJ** [comment]
I upgraded `async-std` to `1.6.0-beta.1` but found a big bench regression, I think maybe the bench code need to be adjusted because the two runtimes seem to work differently.

See also: https://github.com/async-rs/async-std/issues/770

**Comment by GopherJ** [comment]
@xcaptain In this PR: #136, we already be able to run `cargo check` with all our features:

```
cargo test --target  wasm32-unknown-unknown test_wasm --features  --no-default-features --features runtime-async-std,cached,glob,ip,watcher,logging
```

**Comment by GopherJ** [comment]
Ref: https://github.com/async-rs/async-std/issues/843

**Comment by GopherJ** [comment]
with the release of async-std@1.6.4, it's now passing wasm CI check

**Comment by developerworks** [comment]
Maybe this could help: 
https://github.com/WasmEdge/WasmEdge/issues/1402
Wasmedge implement an earlier socket ability
