### ISSUE TITLE
Make effector a stream to optimize enforcing speed by quick return

### ISSUE THREAD

**Issue by GopherJ** [casbin/casbin-rs#125]
See also: https://github.com/casbin/casbin/issues/439

My idea is to make `effector` a writable stream (Sink + Stream), once a policy has been analyzed, we write it into the `stream` and the stream will use different strategy to analyze the result.

Once the final result is produced, we return it as the result of `e.enforce`

**Comment by GopherJ** [comment]
Or maybe we should just implement it in `enforce` method?

**Comment by GopherJ** [comment]
The former makes it more general but harder to implement. The latter is simpler but less general (we need to put everything in enforce method, now it's ok we have only 4 effect strategies but how about having more?)

**Comment by hsluoyz** [comment]
We should extract the effector out. I think the idea about stream sounds good. Is sink + stream a built-in concept/operation in Rust?

**Comment by GopherJ** [comment]
@hsluoyz It's not a built in concept but it's very common. I didn't try to implement it because some potential problems need to be resolved but generally it should be feasible.

**Comment by GopherJ** [comment]
implemented in #142
