### ISSUE TITLE
switch to smol when it's ready

### ISSUE THREAD

**Issue by GopherJ** [casbin/casbin-rs#130]
https://github.com/stjepang/smol is really cool.

It's another async runtime but compatible with tokio and async-std, also it's faster than async-std and tokio (I don't have a figure to prove but people tend to agree on this).

Besides we will be able to target `wasm` because it doesn't rely on `mio`.

I suggest then switch to it when it's ready and remove totally the two features:

- `async-std`
- `tokio`

**Comment by hackerchai** [comment]
> https://github.com/stjepang/smol is really cool.
> 
> It's another async runtime but compatible with tokio and async-std, also it's faster than async-std and tokio (I don't have a figure to prove but people tend to agree on this).
> 
> Besides we will be able to target `wasm` because it doesn't rely on `mio`.
> 
> I suggest then switch to it when it's ready and remove totally the two features:
> 
> - `async-std`
> - `tokio`

Sounds really good. We can give it a try when it's ready.

**Comment by GopherJ** [comment]
async-std = "1.6.0-beta.1"     # Async version of the Rust standard library

has been published using `smol` as runtime

**Comment by GopherJ** [comment]
since async-std will use `smol` we will use `async-std` probably
