### ISSUE TITLE
Dont rebuild all role links

### ISSUE THREAD

**Issue by GopherJ** [casbin/casbin-rs#138]

**Comment by GopherJ** [comment]
See also: https://github.com/casbin/casbin/issues/455

**Comment by GopherJ** [comment]
https://github.com/casbin/casbin-rs/blob/23af2bf5da713515425eda4fc9af1a094ce765ed/src/emitter.rs#L19

A more clever solution is for example, do the change using `EventEmitter`, from `EventData` we can know exactly what happend so nomally we will be able to add/remove the influenced role links

**Comment by UnderTreeTech** [comment]
> https://github.com/casbin/casbin-rs/blob/23af2bf5da713515425eda4fc9af1a094ce765ed/src/emitter.rs#L19
> 
> A more clever solution is for example, using `EventEmitter` to adjust role links, from `EventData` we can know exactly what happend so nomally we will be able to add/remove only the influenced role links instead of rebuild all.

Good idea, does go casbin implement this design pattern?

**Comment by GopherJ** [comment]
@UnderTreeTech Only casbin-rs used this, in casbin-rs we use it for `logging`, `notifying watcher`, `clear CachedEnforcer's TTL cache`

**Comment by GopherJ** [comment]
@UnderTreeTech But also it's not necessary to implement it using EventEmitter` we can also put changes in `build_role_links` function's arguments which maybe more clean.

**Comment by UnderTreeTech** [comment]
> @UnderTreeTech But also it's not necessary to implement it using `EventEmitter` we can also put changes in `build_role_links` function's arguments, which maybe more clean.

LGTM. What's the roadmap to add the feature.
As far I run the model_b_test.go bench by adjusting parameters to 10k roles, 500k users, it costs about 11m and panic(error run too long). So i worry about the performance of casbin much. Do you guys have any plan to optimize performance?

**Comment by GopherJ** [comment]
@UnderTreeTech casbin's enforcing speed is already not bad, what we may need to optimize is like `rebuild role links`.

**Comment by GopherJ** [comment]
Close as solved in #139
