### ISSUE TITLE
Should we stick with rust clippy

### ISSUE THREAD

**Issue by xcaptain** [casbin/casbin-rs#15]
Clippy is a static analysis tool, Recently I tested this project using `cargo clippy` and found a lot of errors and warnings.

![图片](https://user-images.githubusercontent.com/4054836/63236719-6d28e380-c271-11e9-93c8-4e3cec37e395.png)

We have already setup `cargo fmt` in travis-ci, should we fix `cargo clippy` errors before committing?

Setup clippy with `travis-ci` is easy, https://github.com/rust-lang/rust-clippy

**Comment by xcaptain** [comment]
@GopherJ Do you think we should stick with clippy or do you have interest to do this task?

**Comment by GopherJ** [comment]
@xcaptain we should stick and I'll handle it
