### ISSUE TITLE
Add AuthN & AuthZ sections for Rust in our awesome-auth list

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin-rs#160]
Can anyone add Rust to our list? https://github.com/casbin/awesome-auth

![image](https://user-images.githubusercontent.com/3787410/82348362-55ae9f00-9a2b-11ea-80ad-a8b525cee648.png)

**Comment by GopherJ** [comment]
why `authn` is relevant?

**Comment by hsluoyz** [comment]
AuthN is similar area with AuthZ. We want to make this list more useful.

**Comment by GopherJ** [comment]
See: https://github.com/casbin/awesome-auth/pull/17

**Comment by hsluoyz** [comment]
Looks good.
