### ISSUE TITLE
casbin cache

### ISSUE THREAD

**Issue by liergou99** [casbin/casbin-rs#170]
I want to read rules from database on real time, not from the casbin cache,when check the authorities.

**Comment by GopherJ** [comment]
@liergou99 I'm not sure I've understood

> I want to read rules from database on real time, not from the casbin cache,when check the authorities.

Cache is only used to avoid duplicated enforce call. Cache will be cleared once a change on policies was detected.

**Comment by GopherJ** [comment]
@liergou99 hi, does this still cause problem for you?

**Comment by GopherJ** [comment]
close as stale
