### ISSUE TITLE
casbin cache

### ISSUE THREAD

**Issue by liergou99** [casbin/casbin-rs#171]
The problem with caspin caching is as follows:：
       1.If the system is load balanced through multiple servers，It is more convenient to store permission data only through the database，If the cache is used, it is easy to cause data inconsistency among multiple servers
       2.My system has permission tables and does not want to use sqlx-adapter table.

**Comment by hsluoyz** [comment]
@liergou99 change to English.

**Comment by GopherJ** [comment]
@liergou99

1. It's a known issue, I have thought about this, to fix this you need to share cache, casbin-rs exports CacheApi, you can implement your own cache using redis
2. now the table is fixed to: `casbin-rules`, you can have a forked version to achieve your needs, or if you have an idea on making it supports other tables, let us know. PR is welcome

**Comment by GopherJ** [comment]
@liergou99  BTW, we have also this repo if you would like to contribute:

https://github.com/casbin-rs/redis-cache

**Comment by liergou99** [comment]
1. I modified the sql-adapter. The modified sql-adapter uses the tables in my system and completes a simple test, but the current modified program is highly coupled with my system.
2. I think it is very useful to cache permission data through redis. I will try to write about redis-cache, but it may take a little longer. On the one hand, I have company work to complete, on the other hand, I need to understand more casbin architecture

**Comment by GopherJ** [comment]
@hackerchai could you help solving this issue?

BTW @liergou99 why are you using multiple `CachedEnforcer` instance?

**Comment by hackerchai** [comment]
> @hackerchai could you help solving this issue? I know that you are already maybe available
> 
> BTW @liergou99 why are you using multiple `CachedEnforcer` instance?

Get it

**Comment by liergou99** [comment]
Enterprise level projects usually use multiple service nodes to achieve load balancing or dynamic expansion. If each node uses its own memory for data caching, data consistency between nodes cannot be guaranteed.

**Comment by GopherJ** [comment]
It's now https://github.com/casbin-rs/redis-cache, but not published to crates.io yet because it only works with `release-v2.0.0` branch
