### ISSUE TITLE
structured logging

### ISSUE THREAD

**Issue by GopherJ** [casbin/casbin-rs#190]
currently we only have a rough log support, it's hard to to plug in third-party services

**Comment by hsluoyz** [comment]
Good point. @hackerchai @PsiACE can anybody take it?

**Comment by GopherJ** [comment]
Filebeats is a good tool to collect syslog output generated by casbin-rs:

```
filebeat.inputs:
- type: log
  paths:
    - /var/log/*.log
    - /var/path2/*.log
```

**Comment by GopherJ** [comment]
It's now in `release-v2.0.0` branch, casbin-rs `set_logger` method accepts any `slog::Logger` by default it uses also `slog`
