### ISSUE TITLE
setup clog-cli CI

### ISSUE THREAD

**Issue by GopherJ** [casbin/casbin-rs#205]
https://github.com/clog-tool/clog-cli

@PsiACE  would you be interested to take this?

**Comment by PsiACE** [comment]
I will check it and other possible options during the day.

**Comment by PsiACE** [comment]
Are there any special needs? For example, update only when released, see casbin-rs changelog in https://github.com/PsiACE/changelog-action-test/blob/master/CHANGELOG.md

If you think this is okay for now, I will create a PR.

**Comment by PsiACE** [comment]
Note that this is not a clog-cli CI because clog-cli cannot generate correct output. See https://github.com/clog-tool/clog-cli/issues/105 & https://github.com/clog-tool/clog-cli/issues/104.

**Comment by GopherJ** [comment]
@PsiACE Yes it's ok, thanks
