### ISSUE TITLE
Support policy.csv comment or YAML file adapter

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin-rs#213]
See: https://github.com/whamcloud/integrated-manager-for-lustre/pull/2442#discussion_r544421774

We can easily support # as comment grammar in CSV, but the disadvantage is that comment is actually not a part of CSV standard.

Maybe a YAML file adapter would be better. We need to create a new repo for the code, see: https://github.com/casbin-rs/yaml-adapter

Can anyone work on this to fulfill the customer's need?

**Comment by hsluoyz** [comment]
@hackerchai @PsiACE 

/cc @GopherJ

**Comment by hsluoyz** [comment]
Hi @nlinker @mkpankov

Which way do you prefer?

1. "#" as comment grammar in CSV (like in Python)
2. YAML file adapter

**Comment by nlinker** [comment]
> Hi @nlinker @mkpankov
> 
> Which way do you prefer?
> 
> 1. "#" as comment grammar in CSV (like in Python)
> 2. YAML file adapter

Thank you for asking this, I'd have YAML adapter. 
The additional advantages for YAML are:
- the standard escaping syntax, when the resource contains comma or double quote,
- the editors support for the navigations and highlighting.

**Comment by hsluoyz** [comment]
@closetool plz take a look at this issue

**Comment by hsluoyz** [comment]
Hi @nlinker @mkpankov

I think the YAML adapter is basically finished and released to crates.io, can you try it and verify whether it works for you? https://github.com/casbin-rs/yaml-adapter

**Comment by nlinker** [comment]
> Hi @nlinker @mkpankov
> 
> I think the YAML adapter is basically finished and released to crates.io, can you try it and verify whether it works for you? https://github.com/casbin-rs/yaml-adapter

Thank you, Yang Luo! Just FYI: [the authorization PR for IML](https://github.com/whamcloud/integrated-manager-for-lustre/pull/2442) was closed because it has been moved to the Whamcloud's internal repository. It is awesome to see, how prompt the developers of casbin-rs are!
