### ISSUE TITLE
CSV loader deletes double quotes

### ISSUE THREAD

**Issue by Slumber86** [casbin/casbin-rs#214]
I have an ABAC with policy rule with  a model like this:

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub_rule, obj, act

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = eval(p.sub_rule) && r.obj == p.obj && r.act == p.act
```

A policy like this:

```csv
p, r.sub.Status == "ACTIVE", /data1, read

```

And a request like:

```csv
{ Status: "ACTIVE"}, /data1, read
```

When I try to load the policy with CSV loader i get this error:

`ErrorVariableNotFound("ACTIVE")`

Futher investigation suggest that csv-loader removes all `"` from policy CSV making casbin mistake strings for variables. Temporary workaround is to map the values to integers, but using strings would be more correct

**Comment by hsluoyz** [comment]
@PsiACE @hackerchai 

/cc @GopherJ

**Comment by GopherJ** [comment]
@Slumber86 thanks for this important report! it was introduced accidently while fixing: https://github.com/casbin/casbin/issues/518

**Comment by hsluoyz** [comment]
Can we fix it from the code: https://github.com/casbin/casbin-rs/pull/188/files ?

**Comment by hsluoyz** [comment]
@matrixkook can you take this issue?

**Comment by MATRIXKOO** [comment]
I'm Matrixkook. I'd like to take this.

**Comment by GopherJ** [comment]
@MATRIXKOO would you mind reviewing #216 I had some local work yesterday but also look forward to your review/idea.
