### ISSUE TITLE
support semver version

### ISSUE THREAD

**Issue by GopherJ** [casbin/casbin-rs#219]

**Comment by GopherJ** [comment]
currently casbin-rs use fixed version of dependencies, it'll be good to use semver syntax to make it more fuzzy so that cargo can select versions thus avoid two version of `tokio`, `async-std` etc...

**Comment by GopherJ** [comment]
we should also remove lockfile

**Comment by hsluoyz** [comment]
can you do this? @smrpn 

/cc @hackerchai
