### ISSUE TITLE
Consider cargo audit

### ISSUE THREAD

**Issue by smhmayboudi** [casbin/casbin-rs#225]
Please consider this issue https://github.com/jonathandturner/rhai/issues/321

**Comment by schungx** [comment]
`0.19.8` has been unyanked for the time being.

It has a bug that causes errors when using closures (something that casbin doesn't need). That's the reason for the yank.

**Comment by hsluoyz** [comment]
@GopherJ @hackerchai @PsiACE

**Comment by hsluoyz** [comment]
@RobotHuang can you take a look at this issue?

**Comment by RobotHuang** [comment]
@hsluoyz @smhmayboudi we have updated  to 0.19.10. I think that this issue could be closed.

**Comment by hsluoyz** [comment]
@smhmayboudi
