### ISSUE TITLE
tokio 1.0.2 update

### ISSUE THREAD

**Issue by smhmayboudi** [casbin/casbin-rs#226]
Many thanks for all your efforts. As time passes more projects upgrade to tokio 1. Would you please consider it?

**Comment by hsluoyz** [comment]
Ping @GopherJ @hackerchai @PsiACE

**Comment by hsluoyz** [comment]
@hackerchai @PsiACE

**Comment by hackerchai** [comment]
@smhmayboudi  @hsluoyz  see #230
Already upgraded
