### ISSUE TITLE
Relation to Devolutions/casbin-rs?

### ISSUE THREAD

**Issue by kyle-mccarthy** [casbin/casbin-rs#23]
Hi, is there any relation between this project and https://github.com/Devolutions/casbin-rs? 

On the [casbin homepage](https://casbin.org/en/), it links to the other repo, but the [overview page](https://casbin.org/docs/en/overview) links to this repo. The goland and node repo's for casbin also link to the other repo.

**Comment by hsluoyz** [comment]
Thanks for the report. casbin-rs fixed in: https://github.com/casbin/casbin-website/commit/869c28cb3df2942d7bf3a8aef25e0f8b121a8ba2

Can you point me out where is `The goland and node repo's for casbin also link to the other repo.`?

**Comment by hsluoyz** [comment]
Closed as stale.

**Comment by kyle-mccarthy** [comment]
Sorry for the delay. It’s in the readme. https://github.com/casbin/casbin/blob/master/README.md#all-the-languages-supported-by-casbin

I noticed it is in the java one as well so it may be in all the packages under the supported language section.

**Comment by hsluoyz** [comment]
Can you make a PR to fix them?
