### ISSUE TITLE
Please add a GBAC example

### ISSUE THREAD

**Issue by bionicles** [casbin/casbin-rs#235]
Would it be possible to implement Graph-based access control with Casbin?

EX: Pattern-matching on the relationship / traversal from subject to object and /or vice versa?

This could enable a simplified ruleset since we could abstract a lot of rules into a smaller number of traversal patterns...

**Comment by hsluoyz** [comment]
@bionicles is this what you need? https://casbin.org/docs/en/rbac#use-pattern-matching-in-rbac

Or can you give an example (better in Casbin model & policy format) for what you want to achieve?

**Comment by bionicles** [comment]
thanks for the link - that looks similar, however, I find the casbin model configuration files too hard to read because they're so terse and have ridiculous syntax, "r" is unclear, "p", "g" -- these symbols mean nothing without reading a bunch of other docs, lots of one letter terms which require mental unpacking. Right now, looking at Casbin docs, I'd way rather implement the rules myself without Casbin simply to use actual words instead of 1-letter symbols and 3-letter codes. 

Just imagine you're trying to explain this stuff to some non-technical person. It's gonna take forever, and it's gonna sound like total BS, because it's "p alice book group read, g books slash id book group" -- yeah, let me try presenting that syntax to customers, employees, and investors simply. 

It would be handy if the docs clarified if we could use actual words for these, so it would be readable to the newcomers who are typically the consumer of documentation. I'd rather specify mission-critical security and privacy rules in something that reads like plain english, so it would be more interpretable. 

Sorry to be in conflict here, but I really value simplicity and this looks like a whole new language, and it's greek to me! If Casbin configuration were easier to read, I bet it would see much more adoption. But that might be hard to implement and might involve lots of breaking changes...

Anyway, here's more Re: GBAC
specifically i'm interested in http://hl7.org/fhir/security.html#binding but with graph-based access control, based on the set of paths between the requesting user and some data resource

how could one pass in an array of paths from subject to object? 

for example, a practitioner (perhaps a doctor) might be related to a datum in resource through many different possible traversals. How could I pass in this set of paths and pattern-match over the set of them?

Thanks for your work, truly, it's a cool library in a critical niche, I wish I could understand it, but I'm a simpleton...

**Comment by hsluoyz** [comment]
@bionicles 

> Sorry to be in conflict here, but I really value simplicity and this looks like a whole new language, and it's greek to me! If Casbin configuration were easier to read, I bet it would see much more adoption. But that might be hard to implement and might involve lots of breaking changes...

I'm OK to add a more human readable layer on top of the Casbin core grammar. Just replace `r` with `request`, `sub` with `subject`, not hard at all. But could you describe your favored tone? What does the best policy language look like in your imagination?

> for example, a practitioner (perhaps a doctor) might be related to a resource through many many different possible traversals. How could someone pass in this set of paths and pattern-match over the set of them?

Maybe you want this: https://casbin.org/docs/en/rbac#role-hierarchy

**Comment by hsluoyz** [comment]
Closed as stale.

**Comment by bionicles** [comment]
Sorry for being rude. I still think simplicity and clarity would help a lot
