### ISSUE TITLE
get_all_actions get_all_objects

### ISSUE THREAD

**Issue by xiaobeiswift** [casbin/casbin-rs#265]
<img width="683" alt="image" src="https://user-images.githubusercontent.com/31656300/122138647-b51eee80-ce79-11eb-9954-3de4703b9ebc.png">
in management_api.rs,  fieldIndex parameter  hardcoded 1, 2.
But if the tokens of Policy will have an error if it is greater than 4.
ex:
``` p,admin,domain1,data1,read ```  --- "examples/rbac_with_domains_policy.csv"
the function get_all_actions() return "data1".
get_all_objects() return "domain1"

**Comment by hsluoyz** [comment]
@xiaobeiswift this is a known issue. If there are many users complaining about it, we may improve this in future.
