### ISSUE TITLE
Multithreaded environment: RwLock needed around Enforcer with sqlx-adapter?

### ISSUE THREAD

**Issue by bk138** [casbin/casbin-rs#278]
I've got a question about casbin-rs usage: I'm using it with actix-web and the [example states](https://github.com/actix/examples/blob/master/security/casbin/src/main.rs#L40) that the Enforcer should be wrapped in an RwLock. I wonder if this is because of the example using FileAdapter and that the protection by the RwLock can maybe be omitted when using a DB adapter like [sqlx-adapter](https://github.com/casbin-rs/sqlx-adapter)? Or does the RwLock protect state inside the single Enforcer instance? Thanks!

**Comment by hsluoyz** [comment]
@hackerchai

**Comment by hackerchai** [comment]
> I've got a question about casbin-rs usage: I'm using it with actix-web and the [example states](https://github.com/actix/examples/blob/master/security/casbin/src/main.rs#L40) that the Enforcer should be wrapped in an RwLock. I wonder if this is because of the example using FileAdapter and that the protection by the RwLock can maybe be omitted when using a DB adapter like [sqlx-adapter](https://github.com/casbin-rs/sqlx-adapter)? Or does the RwLock protect state inside the single Enforcer instance? Thanks! 

We use RwLock because actix-web is actually multi-threads when handling concurrent requests. In this way, you can use adapter to work with cash in.

**Comment by bk138** [comment]
> We use RwLock because actix-web is actually multi-threads when handling concurrent requests. In this way, you can use adapter to work with cash in.

Yep, the question is more like: is Enforcer thread-safe (maybe only with certain adapters)? https://github.com/casbin/casbin-rs/commit/529554e0a044b20bbbc9607e59a5d053b537b86a kinda hints at that. If it is not, it's maybe a good idea to state that in the docs. Would you accept a PR to the README adding a hint?

**Comment by hackerchai** [comment]
> > We use RwLock because actix-web is actually multi-threads when handling concurrent requests. In this way, you can use adapter to work with cash in.
> 
> Yep, the question is more like: is Enforcer thread-safe (maybe only with certain adapters)? [529554e](https://github.com/casbin/casbin-rs/commit/529554e0a044b20bbbc9607e59a5d053b537b86a) kinda hints at that. If it is not, it's maybe a good idea to state that in the docs. Would you accept a PR to the README adding a hint?

The enforcer is not thread-safe. PR is always welcomed.
