### ISSUE TITLE
Getting a error while setting up rust-basin-example in local environment

### ISSUE THREAD

**Issue by SiddheshKanawade** [casbin/casbin-rs#289]
I was trying to setup the local environment to run [rust-cabin-example](https://github.com/zupzup/rust-casbin-example). I am consistently getting an error saying upgrade to latest version of RUST. I am using 2021 version of rust in project and have tried `cargo fix —edition` but still issue continues. Can someone please help to solve this issue
Following is the screenshot of the issue:

![Screen Shot 2022-02-23 at 4 22 33 PM](https://user-images.githubusercontent.com/85673539/155824627-741a3e10-9e2c-46f5-94e9-2e79e03e8f00.png)

Following is how my _Cargo.toml_ file looks like

![Screen Shot 2022-02-26 at 7 33 00 AM](https://user-images.githubusercontent.com/85673539/155824742-af553f2f-21b3-4619-9592-f7c07321355e.png)

**Comment by PsiACE** [comment]
Do not use rustc directly. I highly recommend that you use cargo for all the work that needs to be done.

**Comment by SiddheshKanawade** [comment]
I have tried using `cargo build` and `cargo test` and then I ran the project using `cargo run`. It worked in my case but not sure why `rustc` gave error. Still this solves the issue in my case, thanks for the help. 
Also, @PsiACE, do we still have to implement Rust version of Casbin server, since this feature is removed from Casbin-rs project (GSOC '22).

**Comment by PsiACE** [comment]
hi @SiddheshKanawade , In GSoC 2021, we have a [casbin-grpc](https://github.com/casbin-rs/casbin-grpc/) that you can consider to improve on it.

**Comment by SiddheshKanawade** [comment]
Sure, I will try to improve on it
Thank you.

**Comment by schungx** [comment]
https://doc.rust-lang.org/rustc/command-line-arguments.html#--edition-specify-the-edition-to-use

`rustc` defaults to `2015`.

`cargo` just passes the correct edition to `rustc`.  If you invoke `rustc` directly, you need to specify the edition yourself.

**Comment by SiddheshKanawade** [comment]
@schungx Thank you for your help, now its clear why rustc gave error.
