### ISSUE TITLE
Rename the package name

### ISSUE THREAD

**Issue by xcaptain** [casbin/casbin-rs#30]
Currently, we use `casbin-rs` as the package name in `Cargo.toml`, would be better to use `casbin` directly. Also the name `casbin` is available, see: https://crates.io/search?q=casbin

**Comment by hsluoyz** [comment]
@xcaptain of course we should use `casbin` directly. For each language's package manager, we usually use `casbin` name, like npmjs, etc. The differentiation like `node-casbin`, `casbin-rs` is mainly for GitHub repo names.

**Comment by hsluoyz** [comment]
Can we release it?

**Comment by xcaptain** [comment]
I will release as soon as possible. please take a look at https://github.com/casbin/casbin-rs/pull/28

**Comment by xcaptain** [comment]
Changed at #28  and the 0.1.0 version just published https://crates.io/crates/casbin
