### ISSUE TITLE
Question About ABAC Usage And Debug

### ISSUE THREAD

**Issue by hxndg** [casbin/casbin-rs#324]
I write a simle code to test abac usage, but it keep telling me somethin of "failed to user enforcer enforce Casbin Evaluation Error: `ErrorMismatchDataType("bool", "()", 1:1)`"
I add the enable_log to trace debug, but rust compiler tell me this function does not exist, so how should i  debug it ? 

```
let rt = runtime::Runtime::new().unwrap();
        let model_path = "reverse_abac_model.conf";
        let result = rt.block_on(async {
            Enforcer::new(model_path, ()).await
        });
        match result {
            Ok(real_enforcer) => {
                // real_enforcer.enable_log(true);
                match real_enforcer.enforce(("a","b","c")) {
                    Ok(unauthorized) => {
                        panic! ("u got be kidding")
                    },
                    Err(e) => panic!("failed to user enforcer enforce {e}"),
                }
                ...
            },
            Err(e) => panic!("failed to init default model, {e}"),
        }
```

**Comment by hsluoyz** [comment]
@hxndg try your model in editor first: https://editor.casbin.org/

**Comment by hxndg** [comment]
> @hxndg try your model in editor first: https://editor.casbin.org/

model file is same with editor "abac with policy" default model, I just paste it from editor. Is there any way to show casbin-rs enforcer process ? enable_log function not find

[request_definition]
r = sub, obj, act

[policy_definition]
p = sub_rule, obj, act

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = eval(p.sub_rule) && r.obj == p.obj && r.act == p.act

**Comment by hsluoyz** [comment]
@hxndg try to run this ABAC 1 test case, it runs well at my side:

![image](https://github.com/casbin/casbin-rs/assets/3787410/a9e7a31d-b1c1-4dde-a6bc-e22ba412fe19)


https://github.com/casbin/casbin-rs/blob/7a6bedbe4dbf1b255ae96fb14d6753b476a2660b/src/enforcer.rs#L1441-L1497

**Comment by hxndg** [comment]
> @hxndg try to run this ABAC 1 test case, it runs well at my side:
> 
> ![image](https://private-user-images.githubusercontent.com/3787410/297235256-a9e7a31d-b1c1-4dde-a6bc-e22ba412fe19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NTU4MzMsIm5iZiI6MTcwNTY1NTUzMywicGF0aCI6Ii8zNzg3NDEwLzI5NzIzNTI1Ni1hOWU3YTMxZC1iMWMxLTRkZGUtYTZiYy1lMjJiYTQxMmZlMTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTlUMDkxMjEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2E2NThkMjhjNjMyZjRlYTBiMzViZGQ5M2JkYzE4YzBiYjM1ZTA0YzcwNjdmODE2ZDVhZTY3MThiMGE0MjhlYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.H5vwHD3bSM20J9lk5whgqYbfM_uAh91yZRr7PEH9Isc)
> 
> https://github.com/casbin/casbin-rs/blob/7a6bedbe4dbf1b255ae96fb14d6753b476a2660b/src/enforcer.rs#L1441-L1497

Thanks for your reply, I change the code to import a default policy file, all things seems alright then.
I guess should not use below code to start a new enforcer without any policy/adapter added.
``` 
Enforcer::new(model_path, ()).await
```
