### ISSUE TITLE
Nightly (2024-02-06) Fails to Build due to old dependency on ahash 0.7.7

### ISSUE THREAD

**Issue by ChosunOne** [casbin/casbin-rs#326]
The latest nightly build (2024-02-06) fails to build casbin due to a dependency on https://github.com/PsiACE/ritelinked which depends on an old version of `ahash`, 0.7.7.  The `ritelinked` crate itself appears to not be maintained as it has not been updated in over two years.

**Comment by ChosunOne** [comment]
My suggestion would be to use the more popular and maintained version of the same thing, https://github.com/kyren/hashlink.

**Comment by hsluoyz** [comment]
@ChosunOne hi, can you make a PR to fix it?

**Comment by ChosunOne** [comment]
I'll make a PR with this issue linked later today
