### ISSUE TITLE
macos m1 build error

### ISSUE THREAD

**Issue by einsli** [casbin/casbin-rs#329]
When I use casbin in my code import by this code 
```toml
casbin = { version = "2.2.0", default-features = false, features = ["runtime-async-std", "cached", "logging"] }
```
I build my code with the following script

```shell
cargo build 
```
error occurd

```PlainText
rror[E0786]: found invalid metadata files for crate `hashbrown`
 --> /Users/xxx/dashmap-5.5.3/src/iter.rs:9:5
  |
9 | use hashbrown::hash_map;
  |     ^^^^^^^^^
  |
  = note: invalid metadata version found: /Users/xxxx/casbin_demo/target/debug/deps/libhashbrown-a1936faada653aca.rmeta

error[E0786]: found invalid metadata files for crate `parking_lot_core`
 --> /Users/xxxxx/dashmap-5.5.3/src/lock.rs:2:5
  |
2 | use parking_lot_core::{ParkToken, SpinWait, UnparkToken};
```

My OS is macos 14.2.1 (23C71)

**Comment by MuZhou233** [comment]
Have you tried delete `target` directory and build again?

**Comment by einsli** [comment]
> Have you tried delete `target` directory and build again?

yes, I delete the target file and build again， but I can still get the error

**Comment by hsluoyz** [comment]
@einsli you should notice that our macOS builds are passing, see: https://github.com/casbin/casbin-rs/actions/runs/7799476498/job/21270359389 . So I think Casbin-RS supports macOS well and it's your own environment's issue for not building it.

![image](https://github.com/casbin/casbin-rs/assets/3787410/a84bd36f-e937-4faf-bc20-ee788c0d2fe5)
