### ISSUE TITLE
Use github actions to auto generate rust doc 

### ISSUE THREAD

**Issue by xcaptain** [casbin/casbin-rs#33]
We can use github actions to generate rust doc and then push to an `gh-pages` branch, so we can have a doc site.

We can learn from https://github.com/rust-analyzer/rust-analyzer/blob/master/.github/workflows/rustdoc.yaml and https://github.com/peaceiris/actions-gh-pages#1-add-ssh-deploy-key

Using this way we need to generate a ssh key pair for github actions so it can commit to this repository.

**Comment by hsluoyz** [comment]
What about using a repo like: https://github.com/casbin-rs/docs?

**Comment by GopherJ** [comment]
#57

**Comment by hsluoyz** [comment]
The docs has been put to: https://casbin.org/casbin-rs/casbin/
