### ISSUE TITLE
Are there plans to implement a string adapter in Rust?

### ISSUE THREAD

**Issue by josecelano** [casbin/casbin-rs#331]
Are there plans to implement a string adapter in Rust like [the one in Go](https://github.com/ShuaiGao/string-adapter)?

See:

- https://casbin.org/docs/model-storage#load-model-from-string
- https://github.com/qiangmzsx/string-adapter

Is it possible to load both the model and the policy from strings?

_Originally posted by @josecelano in https://github.com/casbin/casbin-rs/issues/186#issuecomment-2183069760_

**Comment by hsluoyz** [comment]
Moved to: https://github.com/casbin-rs/string-adapter/issues/1
