### ISSUE TITLE
Add casbin access control hoop for salvo framework.

### ISSUE THREAD

**Issue by andeya** [casbin/casbin-rs#345]
I am a contributor to the [Salvo](https://github.com/salvo-rs/salvo) web framework and have developed the middleware package (https://github.com/andeya/salvo-casbin). Could you please transfer my repository to the Casbin organization and include it in this documentation? (https://casbin.org/zh/docs/middlewares)

# salvo-casbin

[![Crates.io](https://img.shields.io/crates/d/salvo-casbin)](https://crates.io/crates/salvo-casbin)
[![Docs](https://docs.rs/salvo-casbin/badge.svg)](https://docs.rs/salvo-casbin)
[![CI](https://github.com/andeya/salvo-casbin/actions/workflows/ci.yml/badge.svg)](https://github.com/andeya/salvo-casbin/actions/workflows/ci.yml)
[![codecov](https://codecov.io/gh/andeya/salvo-casbin/branch/main/graph/badge.svg)](https://codecov.io/gh/andeya/salvo-casbin)

[Casbin](https://github.com/casbin/casbin-rs) access control hoop for [salvo](https://github.com/salvo-rs/salvo) framework

## Install

Add dependencies to `Cargo.toml`

```bash
cargo add salvo
cargo add salvo-casbin
cargo add tokio --features full
```

## Requirement

**Casbin only takes charge of permission control**, so you need to implement an `Authentication Middleware` to identify user.

For example:
```rust
use casbin::function_map::key_match2;
use casbin::{CoreApi, DefaultModel, Enforcer, FileAdapter};
use salvo::prelude::*;
use salvo_casbin::{CasbinHoop, CasbinVals};

// Handler that immediately returns an empty `200 OK` response.
#[handler]
async fn handler() {}

#[tokio::main]
async fn main() {
    let m = DefaultModel::from_file("examples/rbac_with_pattern_model.conf")
        .await
        .unwrap();

    let a = FileAdapter::new("examples/rbac_with_pattern_policy.csv");

    let casbin_hoop = CasbinHoop::new(Enforcer::new(m, a).await.unwrap(), |_req, _depot| {
        Ok(Some(CasbinVals {
            subject: String::from("alice"),
            domain: None,
        }))
    });

    casbin_hoop
        .write()
        .await
        .get_role_manager()
        .write()
        .matching_fn(Some(key_match2), None);

    let app = Router::new()
        .hoop(casbin_hoop)
        .push(Router::with_path("/pen/1").get(handler))
        .push(Router::with_path("/pen/2").get(handler))
        .push(Router::with_path("/book/<id>").get(handler));
    
    let acceptor = TcpListener::new("127.0.0.1:5800").bind().await;
    Server::new(acceptor).serve(app).await;
}
```

## License

This project is licensed under

* Apache License, Version 2.0, ([LICENSE-APACHE](LICENSE-APACHE) or [http://www.apache.org/licenses/LICENSE-2.0](http://www.apache.org/licenses/LICENSE-2.0))

**Comment by hsluoyz** [comment]
@andeya thanks for the contribution! It seems that I cannot transfer your repo. Can you make PR to this repo: https://github.com/casbin-rs/salvo-casbin to add your code?

**Comment by andeya** [comment]
@hsluoyz  Could you give me permission to submit to the repo? It will also be convenient for me to continuously maintain it later.

**Comment by hsluoyz** [comment]
@andeya done

**Comment by andeya** [comment]
@hsluoyz The repo code has been migrated.
Two environment variables, `CARGO_TOKEN` and `CODECOV_TOKEN`, need to be configured. At the same time, enable the `Read and write permissions` of `GITHUB_TOKEN`.
(I don't have configuration permission.)

**Comment by andeya** [comment]
@hsluoyz  Release failed. I don't have releasing permission. Perhaps I should remove the release workflow？

```
error: failed to publish to registry at https://crates.io/
Caused by:
  the remote server responded with an error (status 403 Forbidden): this crate exists but you don't seem to be an owner. If you believe this is a mistake, perhaps you need to accept an invitation to be an owner before publishing.
Error: Process completed with exit code 101.
```

**Comment by hsluoyz** [comment]
@andeya this repo can directly use `CARGO_TOKEN` as it's an org-level token.

**Comment by hsluoyz** [comment]
Done here. Move to: https://github.com/casbin-rs/salvo-casbin for future discussion
