### ISSUE TITLE
Missing async support (async-std + async adapter)

### ISSUE THREAD

**Issue by GopherJ** [casbin/casbin-rs#43]
casbin and diesel-adapter are synchronous, but it's worth adding async support to casbin and create a new async adapter.

https://github.com/async-rs/async-std
https://github.com/launchbadge/sqlx

The new adapter can be called `sqlx-adapter`, it's not ORM, but it's full asynchronous.

**Comment by hsluoyz** [comment]
lgtm!

**Comment by GopherJ** [comment]
async-std has been added to casbin-rs through #53

**Comment by GopherJ** [comment]
sqlx is not very mature at this point, I'll add a `sqlx-adapter` later. Now we stick to https://github.com/casbin-rs/diesel-adapter

**Comment by GopherJ** [comment]
actix-web uses `tokio` as runtime, it's important to keep the `async-std` runtime and to add another feature called `runtime-tokio`. So that casbin-rs can works asynchronously in actix-web.

**Comment by mehcode** [comment]
> sqlx is not very mature at this point [...]

@GopherJ Is there something in particular you were missing from SQLx? Happy to help prioritize any remaining pieces.

**Comment by GopherJ** [comment]
@mehcode @hackerchai is working on it and I think he has already everything he needs. So it's fine:) Thanks for making this cool library.

**Comment by hackerchai** [comment]
@GopherJ @hsluoyz   sqlx-adapter version 0.1.0 can be reviewed here: https://github.com/casbin-rs/sqlx-adapter/pull/2

**Comment by GopherJ** [comment]
https://crates.io/crates/sqlx-adapter
