### ISSUE TITLE
Missing logger support

### ISSUE THREAD

**Issue by GopherJ** [casbin/casbin-rs#51]
A proper logger is missing util now with the following features:

1. show the request (sub, obj, action) etc
2. show the enforce result
3. show if it's cached result (by adding a prefix [CACHE])

**Comment by PsiACE** [comment]
Interested in dealing with this, in fact, I was initially attracted to summerofcode2020.

**Comment by hsluoyz** [comment]
Hi @PsiACE , thanks for being interesting in Casbin's GSoC! After Google announced the org list, we will see how to proceed with our students on this program. But now you are free for general open-source contribution.

**Comment by PsiACE** [comment]
I'm trying to work on some efforts from now on. Do you have a more specific idea? This seems to be largely a matter of the format of the recorded information.

**Comment by hsluoyz** [comment]
First we can see how Golang's Casbin handles logs: https://casbin.org/docs/en/log-error

But I hope we can extract out a Logger interface, which only consume on metadata like (timestamp, aciton, data, attributes) and can change logging formats.

We should use also the most popular Rust way for logs. So Casbin-RS users can use the same logging mechanism for Casbin-RS and the other components in their system.

**Comment by PsiACE** [comment]
Thanks for your reply, I will try it.

**Comment by GopherJ** [comment]
Hello @PsiACE, thanks for your be interested in contributions, here what's import for the rust version, maybe you have read it.


**Logger system using env_logger**

 - Design Logger trait and implement the default logger which implements Logger trait.
 - Logger can show if the enforcing result is cached or not by the prefix [Cache].
 - Logger support levels (info, debug, error...). Logs can be filtered by specific Level.
 - Logs are by default colorful.

**Comment by PsiACE** [comment]
@GopherJ 

Recently, I made some simple surveys. It seems that what we need to add is a middleware-like recording method? If this is the case, I would suggest a reference to some web frameworks and only provide log content in a specific format rather than limiting the overall logging approach.

The advantage of such an easy-to-see is that users can use their own recording system and avoid conflicts caused by the logger.

**Comment by PsiACE** [comment]
Actually, I think the important dependency we need is just the **log** crate. 

If we do need a logger, not just a middleware, please remind me. This allows other designs to be performed before designing the internal recording method.

**Comment by GopherJ** [comment]
@PsiACE Yes you are right I think that we only need log crate.  We don't need a middleware like logger.  The logger is specific for multiple reasons:

1. help user to debug and find security attack
2. help developers to debug

To achieve this we need to be able to filter logs using specific log level like Info or Debug. 

Log crate is good enough to achieve this, env_logger should be used by users. Sorry for make it confused;)

**Comment by PsiACE** [comment]
I'm glad we have a consensus, but it is worth pointing out that we may indeed need a middleware to assist in this, so that some potentially useful information can be recorded automatically.

**Comment by GopherJ** [comment]
@PsiACE Hello, do you have some lines of code to show how does it look like?

I'm not so sure about the benefits of middleware-like logger.

**Comment by PsiACE** [comment]
This is my personal superficial knowledge.

Obviously, middleware-like loggers work internally, providing only the messages to be logged. Just like:
- https://github.com/http-rs/tide/blob/master/src/middleware/logger.rs
- https://github.com/seanmonstar/warp/blob/master/src/filters/log.rs

The general logger is selected by the user and work externally to provide more content.
- https://github.com/sebasmagri/env_logger/
- https://github.com/seanmonstar/pretty-env-logger
- https://github.com/PsiACE/loge

**Comment by GopherJ** [comment]
@PsiACE Ok I finally understood what you would like to have, if I understand correctly you want something like this:

```rust
use casbin::prelude::*;

#[async_std::main]
async fn main() {
    let model = Model::from_file("path/to/model.conf")?;
    let adapter = FileAdapter::new("path/to/policy.csv");

    let e = Enforcer::new(Box::new(model),Box::new(adapter)).await?;
    // plug the logger into enforcer
    e.logger(SpecificLogger::default())
}
```
right?

**Comment by PsiACE** [comment]
You're right. Specifically, I think this may be the way we enable logging.

In fact, we still need `env_logger::init();`. This allows the log messages to be output correctly.

**Comment by GopherJ** [comment]
Ok I think this is pretty good option, the important thing of this proposal to have a `DefaultLogger` out of box so that users can use without coding their own.

**Comment by GopherJ** [comment]
@PsiACE Hello are you still on this?

**Comment by PsiACE** [comment]
> @PsiACE Hello are you still on this?

Yep. To some extent, I hope it can be my gsoc project, but I will also consider making some general contribution.

**Comment by GopherJ** [comment]
No problem @PsiACE , I just would like to make sure there is someone on it so I can do other things.

**Comment by GopherJ** [comment]
Let's move to #84
