### ISSUE TITLE
Database transactions similar api `addPolicies`, `removePolicies` 

### ISSUE THREAD

**Issue by GopherJ** [casbin/casbin-rs#55]
See https://github.com/casbin/node-casbin/issues/105

**Comment by GopherJ** [comment]
see #59 

More unit tests need to be added around this, I'll add them when I got time. There are also many work regarding `diesel-adapter`.

It must be able to do transaction.

**Comment by drholmie** [comment]
Hey there! I'm interested in this issue and wanted to know if I can help out with the unit tests.

**Comment by GopherJ** [comment]
@drholmie Hello, thanks for being interested in this. It's important to have these methods, could you help test the following methods:

```
    async fn add_policies(&mut self, paramss: Vec<Vec<&str>>) -> Result<bool>;
    async fn remove_policies(&mut self, paramss: Vec<Vec<&str>>) -> Result<bool>;
    async fn add_named_policies(&mut self, ptype: &str, paramss: Vec<Vec<&str>>) -> Result<bool>;
async fn remove_named_policies(&mut self, ptype: &str, paramss: Vec<Vec<&str>>)
        -> Result<bool>;
    async fn add_grouping_policies(&mut self, paramss: Vec<Vec<&str>>) -> Result<bool>;
    async fn remove_grouping_policies(&mut self, paramss: Vec<Vec<&str>>) -> Result<bool>;
  async fn add_named_grouping_policies(
        &mut self,
        ptype: &str,
        paramss: Vec<Vec<&str>>,
    ) -> Result<bool>;
 async fn remove_named_grouping_policies(
        &mut self,
        ptype: &str,
        paramss: Vec<Vec<&str>>,
    ) -> Result<bool>;
async fn add_permissions_for_user(
        &mut self,
        user: &str,
        permissions: Vec<Vec<&str>>,
    ) -> Result<bool>;
  async fn add_roles_for_user(
        &mut self,
        user: &str,
        roles: Vec<&str>,
        domain: Option<&str>,
    ) -> Result<bool>;
```

Currently we haven't make diesel-adapter supports this, ideally we should have `diesel-adapter` supports this by using transaction.

**Comment by GopherJ** [comment]
diesel-adapter now has also:

```rust
add_policies
remove_policies
```

See https://github.com/casbin-rs/diesel-adapter/pull/15

**Comment by hsluoyz** [comment]
Closed as resolved.

**Comment by drholmie** [comment]
Hey there @GopherJ wanted to clarify a few things. Firstly, should I open a new issue to better track the completion of tests? Secondly, should I also follow the double insert and remove checks as mentioned in the `test_modify_policy_api()`:
```
...
        e.remove_policy(vec!["alice", "data1", "read"])
            .await
            .unwrap();
        e.remove_policy(vec!["bob", "data2", "write"])
            .await
            .unwrap();
        e.remove_policy(vec!["alice", "data1", "read"])
            .await
            .unwrap();
        e.add_policy(vec!["eve", "data3", "read"]).await.unwrap();
        e.add_policy(vec!["eve", "data3", "read"]).await.unwrap();
...
```
for `remove_policies` and `add_policies`  as well?

**Comment by GopherJ** [comment]
Hello @drholmie , yes u can open a new issue to better track the completion of tests.

Yes u can do that.

**Comment by drholmie** [comment]
Thanks for the go ahead @GopherJ !
