### ISSUE TITLE
Add an example to Actix web examples repo

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin-rs#63]
We should add a Casbin example to: https://github.com/actix/examples

And list Casbin into their README.

**Comment by hsluoyz** [comment]
@GopherJ @PsiACE

**Comment by hsluoyz** [comment]
Someone on actix-web's Gitter is requesting this feature: https://gitter.im/actix/actix-web

![image](https://user-images.githubusercontent.com/3787410/75618505-3c275500-5baa-11ea-9455-591017b5f422.png)

**Comment by PsiACE** [comment]
I just completed a simple example, you can check in a moment.

**Comment by PsiACE** [comment]
@hsluoyz 

Please check https://github.com/PsiACE/actix-casbin-example first. 
If everything is OK, we can add it to actix-example or elsewhere.

**Comment by hsluoyz** [comment]
@GopherJ

**Comment by GopherJ** [comment]
Looks good to me, we can add different examples to show different features. Now we just start from: https://github.com/PsiACE/actix-casbin-example 

Thanks for it.

**Comment by hsluoyz** [comment]
Please make PR to: https://github.com/actix/examples

**Comment by PsiACE** [comment]
See https://github.com/actix/examples/pull/264, I just opened this pr.

**Comment by hsluoyz** [comment]
Good. Thanks.

Also a update from customer: https://gitter.im/actix/actix-web

**Comment by PsiACE** [comment]
He need an example of ACL model. I will update later.

**Comment by GopherJ** [comment]
@PsiACE Thanks!

**Comment by PsiACE** [comment]
@GopherJ 

Please check https://github.com/PsiACE/casbin-examples/tree/actix_fileadapter_acl/actix_fileadapter_acl

I think this can be used as a simple example.

**Comment by PsiACE** [comment]
> 参见[actix / examples＃264](https://github.com/actix/examples/pull/264)，我刚刚打开了此公关。



> See [actix/examples#264](https://github.com/actix/examples/pull/264), I just opened this pr.

Done!

**Comment by hsluoyz** [comment]
Don't forget advertising it next time !

Like I did: https://github.com/actix/examples/pull/267
