### ISSUE TITLE
Role inheritance problem in rbac.rs

### ISSUE THREAD

**Issue by xcaptain** [casbin/casbin-rs#7]
The current implementation of role inheritance has a big problem, it can handle direct link between 2 roles but can't handle indirect links like user -> role -> role.

```rust
#[test]
fn test_role() {
    let mut rm = DefaultRoleManager::new(3);
    rm.add_link("u1", "g1", vec![]);
    rm.add_link("u2", "g1", vec![]);
    rm.add_link("u3", "g2", vec![]);
    rm.add_link("u4", "g2", vec![]);
    rm.add_link("u4", "g3", vec![]);
    rm.add_link("g1", "g3", vec![]); // problem occurs, u1 is already in g1, but can't infer that u1 is also in g3
    rm.print_roles();
}
```

the print result is:

```text
{
    "g3": Role { name: "g3", roles: [] }, 
    "u2": Role { name: "u2", roles: [Role { name: "g1", roles: [] }] }, 
    "u1": Role { name: "u1", roles: [Role { name: "g1", roles: [] }] }, 
    "g1": Role { name: "g1", roles: [Role { name: "g3", roles: [] }] }, 
    "u3": Role { name: "u3", roles: [Role { name: "g2", roles: [] }] }, 
    "u4": Role { name: "u4", roles: [Role { name: "g2", roles: [] }, Role { name: "g3", roles: [] }] }, 
    "g2": Role { name: "g2", roles: [] }
}
```

When using `has_link` to check link between `u1` and `g3`, we will iterate over roles in `u1` that is `g1`, but this `g1` has no related roles, while in fact in role manager, `g1` has a related role `g3`.

This problem occurs because we are constructing `Role` using a clone

```rust
#[derive(Clone, Debug)]
pub struct Role {
    pub name: String,
    pub roles: Vec<Role>,
}
```
So when a role changes, it's original clone doesn't change. I have 2 ideas to solve this problem:

1. Keep using a clone, so when `g1` has changed(added to g3), all roles related with g1 must be updated, that is `u1` becomes

    ```text
    "u1": Role { name: "u1", roles: [Role { name: "g1", roles: [Role { name: "g3", roles: [] }] }] }, 
    ```
2. Pass by reference using `Rc`
3. Copy `all_roles` in `DefaultRoleManager` to every `Role` object, since `all_roles` has all the role  infomations.

I will try the second way first. @GopherJ @XanthusL Do you have any ideas on this problem?

**Comment by DevinR528** [comment]
Here is a link to another [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=4ddbfd5c2e40462ac24768b2f8a5c338). if that doesn't help message me and I can actually clone this repo and work on it for a bit if you want me to. Good luck :+1:!!

**Comment by xcaptain** [comment]
@DevinR528 Thank you man, contributions for this project are welcomed. can you help review this commit? https://github.com/casbin/casbin-rs/pull/9
