### ISSUE TITLE
covert rule: Vec<&str> to rule: Vec<String>

### ISSUE THREAD

**Issue by GopherJ** [casbin/casbin-rs#73]
At the beginning we would like to use &str because the conversion from String to &str is cheap.

However, if we consider the production environment and the real use case, we will find it's hard to generate &str with the "correct" lifetime ('static).

For example:

```rust
fn fetch_policies_from_db(conn: &Conn) -> Vec<&str> {
 // hard to implement because &str borrows policies (String) but policies will be released after this function call
}
```

The better solution is to have: `Into<String>` but we need to guarantee it's `Send` and `Sync`.

**Comment by hackerchai** [comment]
I am working on this.

**Comment by hackerchai** [comment]
#75 pull request fixed.

**Comment by hackerchai** [comment]
#75 pull request fixed.
