### ISSUE TITLE
GSOC & Non-GSOC: gitter team link

### ISSUE THREAD

**Issue by GopherJ** [casbin/casbin-rs#80]
Here the link where we'll use for GSOC casbin-rs and future communication on improving casbin-rs. Please join if you would like to do contributions on casbin-rs or if you have sent casbin-rs proposals.

Workspace: casbin-rs@slack.com

Join: [click me](https://join.slack.com/t/casbin-rsslackcom/shared_invite/zt-d965ofhe-yBKjoYn1S2sFJLq1O7k4mA)

**Comment by GopherJ** [comment]
@hackerchai @DevinR528 @PsiACE and the others.

**Comment by hackerchai** [comment]
Get it. Already in.

**Comment by hsluoyz** [comment]
Hi @GopherJ , why don' use Gitter?

**Comment by GopherJ** [comment]
guys, let's use gitter instead

**Comment by hsluoyz** [comment]
It has been 3 months and a lot of things have changed.. Well, currently I'm suggesting our own forum: https://forum.casbin.org/ instead of Gitter.

**Comment by GopherJ** [comment]
@hsluoyz How can I make a badge for forum? and add it to casbin-rs & casbin golang

**Comment by hsluoyz** [comment]
Good idea! Custom badges can be made here: https://shields.io/

**Comment by GopherJ** [comment]
@hsluoyz How about this one:

https://img.shields.io/badge/Forum-Join%20chat-%23cde201

**Comment by GopherJ** [comment]
Join chat is kind of strange because it's not like gitter, it's more for article.

https://img.shields.io/badge/Forum-join-%23cde201

**Comment by GopherJ** [comment]
You can already find a badge in README.md

**Comment by hsluoyz** [comment]
I see it. Thanks!
