### ISSUE TITLE
GSOC: actix actor,actix middleware

### ISSUE THREAD

**Issue by GopherJ** [casbin/casbin-rs#82]
- [x] implement an actix casbin actor which accepts messages of rbac request (subject, domain, object, action and more). The actor will return the result of enforcing.
- [x] implement an actix middleware using actix-web-httpauth and actix casbin actor

Please comment below if you have sent proposal and if you'll work on this.

**Comment by hackerchai** [comment]
I have sent my proposal on this issue.@GopherJ

**Comment by hackerchai** [comment]
The actor is finished. see https://github.com/casbin-rs/actix-casbin/pull/3.

Please update the todo.

**Comment by GopherJ** [comment]
See: 

- https://github.com/casbin-rs/actix-casbin-auth
- https://github.com/casbin-rs/actix-casbin
