### ISSUE TITLE
GSOC: Shared Redis TTL cache

### ISSUE THREAD

**Issue by GopherJ** [casbin/casbin-rs#83]
- [x] Design Cache trait, make CachedEnforcer being able to accept external cache.
- [x] Implement redis TTL cache.

Please comment below if you have sent proposal and if you'll work on this.

**Comment by GopherJ** [comment]
This purpose of a `shared redis TTL cache` is to be able to use the same cache with multiple enforcers.

**Comment by hsluoyz** [comment]
@hackerchai

**Comment by hackerchai** [comment]
> @hackerchai 

Get it. It's in the list of my plan.

**Comment by GopherJ** [comment]
It's now https://github.com/casbin-rs/redis-cache, not published to crates.io yet
