### ISSUE TITLE
GSOC: logger system

### ISSUE THREAD

**Issue by GopherJ** [casbin/casbin-rs#84]
- [ ] Design Logger trait and implement the default logger which implements Logger trait.
- [ ] Logger can show if the enforcing result is cached or not by the prefix [Cache].
- [ ] Logger support levels (info, debug, error...). Logs can be filtered by specific Level.
- [ ] Logs are by default colorful.

Please comment below if you have sent proposal and if you'll work on this.

**Comment by GopherJ** [comment]
As I know @PsiACE  is working on this

**Comment by PsiACE** [comment]
May be useful discussion in the past https://github.com/casbin/casbin-rs/issues/51

**Comment by GopherJ** [comment]
Close as solved in #134 , I just implemented a simple logger there based on `log` crate.
