### ISSUE TITLE
More examples for policies.

### ISSUE THREAD

**Issue by lucaskenda** [casbin/casbin-rs#88]
Hi!

Do you have an example to add new policies from a function, not just a file?
I saw that you can use a MemoryAdapter but I can't make it work.

```
let adapter = FileAdapter::new("/policy.csv");
let e = Enforcer::new(Box::new(model), Box::new(adapter)).await.unwrap();
let enforce = e.enforce(&["alice", "/admin/users", "GET"]).unwrap();
println!("Result: {}", enforce);
```

Thanks!
Lucas

**Comment by GopherJ** [comment]
Hello @lucaskenda , we have a bunch of functions that you can use: https://github.com/casbin/casbin-rs/blob/master/src/management_api.rs

You'll need `use casbin::prelude::*`

**Comment by lucaskenda** [comment]
I've managed to make it work!

I'm creating the MemoryAdepter like this:

let m1 = MemoryAdapter {
  policy: IndexSet::new(),
};

its ok?

```
let mut e = Enforcer::new(Box::new(model), Box::new(m1)).await.unwrap();

e.add_policy(vec!["admin".to_string(), "/admin/new/*".to_string(), "GET".to_string()]).await.unwrap();
e.add_grouping_policy(vec!["alice".to_string(), "admin".to_string()]).await.unwrap();

let enforce = e.enforce(&["alice", "/admin/new/lala", "GET"]).unwrap();

println!("Enforcer: {}", enforce);
```
Thanks @GopherJ!!!

**Comment by GopherJ** [comment]
We have also db adapters if you need persistence.

https://github.com/casbin-rs/diesel-adapter 

and

https://github.com/casbin-rs/sqlx-adapter/pulls it's not finished yet but will come soon.

You can also use `MemoryAdapter::default()` it's better because we will make policy hidden soon
