### ISSUE TITLE
automate package release

### ISSUE THREAD

**Issue by GopherJ** [casbin/casbin-rs#90]
See: https://github.com/semantic-rs/semantic-rs

**Comment by GopherJ** [comment]
Let's use #89 for testing

**Comment by PsiACE** [comment]
Do you mean we need to migrate the [existing auto release](#62 ) to semantic release?

**Comment by GopherJ** [comment]
I mean when we accept a PR, I would like to use sematic-rs for deciding the new version and then after accepting the new PR.

It should be able to create a new git tag

**Comment by GopherJ** [comment]
Maybe we don't need to migrate but just adding semantic-rs for version discoversing

**Comment by PsiACE** [comment]
I will try it. Actually, I've written it, but I haven't tested it

**Comment by PsiACE** [comment]
See #100

**Comment by hsluoyz** [comment]
@GopherJ is this already done?

**Comment by hackerchai** [comment]
> @GopherJ is this already done?

This is still remaining to be done. I am working on this.

**Comment by PsiACE** [comment]
There are two points to note:

- #100 I have completed these tasks, but I have commented out the part that works
- [semantic-rs](https://github.com/semantic-rs/semantic-rs): The project has been archived, we need an alternative.

@hsluoyz @hackerchai

**Comment by hackerchai** [comment]
> There are two points to note:
> 
> - #100 I have completed these tasks, but I have commented out the part that works
> - [semantic-rs](https://github.com/semantic-rs/semantic-rs): The project has been archived, we need an alternative.
> 
> @hsluoyz @hackerchai 

I have communicated with @GopherJ , we agree to use https://github.com/github/semantic to do this job.

**Comment by PsiACE** [comment]
> > There are two points to note:
> > 
> > * #100 I have completed these tasks, but I have commented out the part that works
> > * [semantic-rs](https://github.com/semantic-rs/semantic-rs): The project has been archived, we need an alternative.
> > 
> > @hsluoyz @hackerchai
> 
> I have communicated with @GopherJ , we agree to use https://github.com/github/semantic to do this job.

Sounds good, do it.

**Comment by GopherJ** [comment]
@PsiACE @hackerchai just to correct, it's: https://github.com/semantic-release/semantic-release which should be fine

**Comment by GopherJ** [comment]
Finally I made it works using something like this:


https://github.com/casbin/casbin-rs/blob/master/.github/workflows/release.yml
