### ISSUE TITLE
Add actix-casbin-auth to Actix official middleware list

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin-rs#92]
We have very active development for Casbin-RS now. However, our popularity is still under my estimation (129 stars). I hope we can do more advertisement in future to let people know and use our project.

The first thing we should do is to add Casbin middleware: https://github.com/actix/examples/tree/master/casbin to Actix official middleware list: https://actix.rs/docs/middleware/ . So Actix website visitors will also come to our GitHub page.

Can anyone work on this?

**Comment by GopherJ** [comment]
I'll consider making a good actix middleware

**Comment by GopherJ** [comment]
I had a thought on this. The first thing we need is an actix casbin actor.

```rust
struct CasbinActor {
  enforcer: Option<Enforcer>
}
```

we use `casbin::TryIntoAdapter, casbin::TryIntoModel` for creating it.

```
use casbin::{TryIntoAdapter, TryIntoModel};
impl CasbinActor {
  pub async fn new<M: TryIntoModel, A: TryIntoAdapter>(m: M, a: A) -> Result<Enforcer> {}
}
```

**Comment by GopherJ** [comment]
Then we define our message:

```rust
use casbin::Result;
use actix::Message;

pub enum CasbinCmd {
   Enforce(Vec<String>),
   AddPolicy(Vec<String>),
   AddPolicies(Vec<Vec<String>>),
   RemovePolicy(Vec<String>),
   RemovePolicies(Vec<Vec<String>>)
   ...
}


impl Message for CasbinActor {
    type Result = Result<bool>;
}
```

**Comment by GopherJ** [comment]
At last we should implement:

```
impl Supervised for CasbinActor {
    fn restarting(&mut self, _: &mut Self::Context) {
        self.enforcer.take();
    }
}

impl Handler<CasbinCmd> for CasbinActor {
    type Result = ResponseActFuture<Self, Result<bool>>;

    fn handle(&mut self, msg: CasbinCmd, _: &mut Self::Context) -> Self::Result {
    ...
    }
}

```

**Comment by GopherJ** [comment]
Users can then register `CasbinActor` on `actix-wb::App`.

In our middleware we access casbin enforcer by:

```rust
    if let Some(state) = req.app_data::<Enforcer>() {
     // use casbin for access control
    } else {
     // deny the request
    }
```

**Comment by GopherJ** [comment]
The main problem of this idea is **Users need to register casbin enforcer on app_data**.

How can we register an app data while creating a middleware?

**Comment by hackerchai** [comment]
I am working on this issue. @hsluoyz  @GopherJ

**Comment by GopherJ** [comment]
See also: https://github.com/actix/actix-web/issues/1444

**Comment by hackerchai** [comment]
The actor is finished. see https://github.com/casbin-rs/actix-casbin/pull/3.

**Comment by rakeen01** [comment]
I was interested to work on this issue (https://github.com/casbin/Casbin.NET/issues/24) however working on a good actix software also seems interesting. Is there already a teambase working on this I can connect with?

**Comment by hsluoyz** [comment]
Have we put our product here? https://actix.rs/docs/middleware/

**Comment by hackerchai** [comment]
> Have we put our product here? https://actix.rs/docs/middleware/
> 
> We can find the source code of that website and make a PR for it to add.

@hsluoyz  As far as I know, the only repo of Actix example is https://github.com/actix/examples/tree/master/casbin . I have finished the actor while the middleware is still work-in-progress. When the middleware is done, I will send a PR to https://github.com/actix/examples/tree/master/casbin.

**Comment by PsiACE** [comment]
@hackerchai  You can provide a separate example with middleware. In addition, the example also needs to be added to [casbin-rs/examples](https://github.com/casbin-rs/examples).

**Comment by hsluoyz** [comment]
I'm talking about how to advertise Casbin-RS better on Actix website: https://github.com/actix/actix-website

https://github.com/actix/actix-website/blob/master/content/docs/middleware.md is the source code of https://actix.rs/docs/middleware/

Can anyone make a PR to add Casbin to their website?

**Comment by PsiACE** [comment]
@hsluoyz The link you gave is about official middleware, but we are a third party, so it may not be suitable.

**Comment by hackerchai** [comment]
> @hackerchai You can provide a separate example with middleware. In addition, the example also needs to be added to [casbin-rs/examples](https://github.com/casbin-rs/examples).

@PsiACE  BTW, there is a mistake in the [middleware](https://casbin.org/docs/en/middlewares) page of the casbin official website. The `actix-casbin` link in Rust section is not a middleware but a simple example using actix-web. The [actix-casbin](https://github.com/casbin-rs/actix-casbin) now refers to the Actix runtime actor. We should call the official casbin middleware [actix-casbin-auth](https://github.com/casbin-rs/actix-casbin-auth). Maybe you can rename  `actix-casbin` to `actix-simple-example` or something else.

**Comment by hackerchai** [comment]
#82 Middleware has been implemented.

**Comment by hsluoyz** [comment]
@hackerchai thanks.

Waiting for Actix guys' decision: https://github.com/actix/actix-website/issues/170

**Comment by hackerchai** [comment]
> @hackerchai thanks.
> 
> Waiting for Actix guys' decision: https://github.com/actix/actix-website/issues/170

@hsluoyz Thanks for your work. I will track that issue and implement an actix example using actix-casbin-middleware  as soon as possible.

**Comment by hsluoyz** [comment]
Made a PR: https://github.com/actix/actix-website/pull/205
