### ISSUE TITLE
Make rocket-authz middleware

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin-rs#93]
Rocket is one of the top web frameworks in Rust. We already made a Actix middleware (https://github.com/casbin/casbin-rs/issues/92) but haven't got a Rocket one.

I think this demo (https://github.com/oiatz/Rocket_Casbin_Demo) is not enough. We will need a full-fledged rocket-authz middleware here: https://github.com/casbin-rs/rocket-authz

The Rocket community has urgent need for good authorization:

- https://github.com/SergioBenitez/Rocket/issues/8
- https://github.com/SergioBenitez/Rocket/search?q=auth&type=Issues

**Comment by GopherJ** [comment]
Who can help on `Rocket`?

**Comment by GopherJ** [comment]
seems @hackerchai  wants to work on this. I'm not sure if Rocket supports middleware...

**Comment by hackerchai** [comment]
I will check it these days.@GopherJ

**Comment by hsluoyz** [comment]
Can anyone work on this?

**Comment by hackerchai** [comment]
> Can anyone work on this?

@hsluoyz I have researched for rocket middleware. I will take this task. If anyone can implement it right now it is also welcomed.

**Comment by hackerchai** [comment]
> Can anyone work on this?

@hsluoyz I think this issue is high priority. I will start to work on this right now.

**Comment by hsluoyz** [comment]
@GopherJ @nodece @hackerchai @PsiACE @kingiw any update on this issue?

**Comment by hackerchai** [comment]
> @GopherJ @nodece @hackerchai @PsiACE @kingiw any update on this issue?

@hsluoyz I am working on this.

**Comment by hsluoyz** [comment]
@hackerchai OK. I have created the repo here: https://github.com/casbin-rs/rocket-authz. Looking forward to your progress and PRs! This step means a lot to us and should be highly prioritized.

**Comment by hackerchai** [comment]
> @hackerchai OK. I have created the repo here: https://github.com/casbin-rs/rocket-authz. Looking forward to your progress and PRs! This step means a lot to us and should be highly prioritized.

@hsluoyz Now the current job in my hand is making real-word-examole using actix casbin middleware. After done that, I will put myself in the rocket middeware.

**Comment by simoin** [comment]
Just need to add Enforcer to Rocket State, and get this in Request Guards.
I've written a demo for this [Rocket_Casbin_Demo](https://github.com/simoin/Rocket_Casbin_Demo)

**Comment by hsluoyz** [comment]
@simoin can you add a README?

**Comment by simoin** [comment]
@hsluoyz Done

**Comment by hsluoyz** [comment]
I'm not an expert on either Rust or Rocket. @GopherJ @hackerchai @PsiACE  Can you give some comments on: https://github.com/simoin/Rocket_Casbin_Demo ?

**Comment by hackerchai** [comment]
> Just need to add Enforcer to Rocket State, and get this in Request Guards.
> I've written a demo for this [Rocket_Casbin_Demo](https://github.com/simoin/Rocket_Casbin_Demo)

@simoin Thanks for your work. Maybe [Fairing](https://rocket.rs/v0.4/guide/fairings/) is a better method to implement Casbin middleware for Rocket.

**Comment by simoin** [comment]
@hackerchai  Exactly, you could refer to rocket_contrib::database do

**Comment by hsluoyz** [comment]
@simoin can you add this middleware to our official site?

**Comment by simoin** [comment]
@hsluoyz it is just a binary, not a middleware library.

**Comment by hsluoyz** [comment]
@simoin Can it be regarded as an example project to show how to integrate Casbin-RS into Rocket?

**Comment by simoin** [comment]
I've rewrite the proj with Fairing.

**Comment by hsluoyz** [comment]
OK. Can you add this to our official site?

**Comment by simoin** [comment]
@hsluoyz I've sent a PR to casbin-website.

**Comment by hsluoyz** [comment]
@simoin thanks! Merged: https://github.com/casbin/casbin-website/pull/122

**Comment by hackerchai** [comment]
see https://github.com/casbin-rs/rocket-authz
