### ISSUE TITLE
split code into multiple features

### ISSUE THREAD

**Issue by GopherJ** [casbin/casbin-rs#97]
some times users just need part of all the features. It's important to let users choose what they want so that we can decrease the binary size.

We can have the following features:

- `cached` => add the dependency: **ttl_cache**, default enabled: **false**
- `glob` => add the dependency: **globset**, default-enabled: **true**
- `logging` => add the dependency: **log** , default-enabled: **false**, [done]
- `ip` => add the dependency: **ip_network**, default-enabled: **false**
- `watcher` => add `EventEmitter`, every policy change will need to clone the changes and pass it to watcher which added some overhead, default-enabled: **false**

**Comment by hackerchai** [comment]
I am working on this. @GopherJ

**Comment by hsluoyz** [comment]
Any update?

**Comment by hackerchai** [comment]
> Any update?
I am still waiting some features such as sync to be done. Once these are finished, this issue will be quickly solved.

**Comment by GopherJ** [comment]
@hackerchai we will not have `sync` feature anymore because it requires breaking changes on the api.

Also it's basically a wrapper so users can also wrap Enforcer inside `Arc<RwLock<...>>`

**Comment by hackerchai** [comment]
> @hackerchai we will not have `sync` feature anymore because it requires breaking changes on the api.
> 
> Also it's basically a wrapper so users can also wrap Enforcer inside `Arc<RwLock<...>>`

So we can implement this issue right now?

**Comment by GopherJ** [comment]
@hackerchai Yes

**Comment by hackerchai** [comment]
> @hackerchai Yes

Get it. I think we should open an issue with the roadmap which contains to-dos.

**Comment by GopherJ** [comment]
Solved in #136
